In [4]:
import numpy as np   # biblioteca numpy 
import sys  # biblioteca sys


In [5]:
a =  [1,2,3,4,5]       # array 

b = np.array([1,2,3,4,5])   # array numpay

print(a)

print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
sys.getsizeof(a)  # bytes lista a



104

In [7]:
b.nbytes  # bytes lista b  (o numpy aloca menos memória)

40

In [17]:
# array 1D

d1 = np.array([1,2,3])

print(d1)


[1 2 3]


In [18]:
d1.shape   # formato da array d1

(3,)

In [15]:
d1.ndim  # 1 dimensão

2

In [16]:
d1.dtype

dtype('int64')

In [23]:
# array 2D

d2 = np.array([[1,2,3], [4,5,6]])

print(d2)

[[1 2 3]
 [4 5 6]]


In [25]:
d2.shape   # formato da array d2

(2, 3)

In [34]:
d2.ndim

2

In [26]:
d2.dtype

dtype('int64')

In [30]:
# array 3D

d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
d3.shape   # formato da array d3

(2, 2, 2)

In [33]:
d3.ndim

3

In [32]:
d3.dtype

dtype('int64')

In [40]:
a = np.array([2,3,4])

b = np.array([2,3,4])

In [44]:
result = np.add(a, b)
print(result)

[4 6 8]
