In [1]:
import numpy as np   # biblioteca numpy 
import pandas as pd
import sys  # biblioteca sys


In [2]:
a =  [1,2,3,4,5]       # array 

b = np.array([1,2,3,4,5])   # array numpay

print(a)

print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [3]:
sys.getsizeof(a)  # bytes lista a



104

In [4]:
b.nbytes  # bytes lista b  (o numpy aloca menos memória)

40

In [5]:
# array 1D

d1 = np.array([1,2,3])

print(d1)


[1 2 3]


In [6]:
d1.shape   # formato da array d1

(3,)

In [7]:
d1.ndim  # 1 dimensão

1

In [16]:
d1.dtype

dtype('int64')

In [8]:
# array 2D

d2 = np.array([[1,2,3], [4,5,6]])

print(d2)

[[1 2 3]
 [4 5 6]]


In [9]:
d2.shape   # formato da array d2

(2, 3)

In [34]:
d2.ndim

2

In [26]:
d2.dtype

dtype('int64')

In [10]:
# array 3D

d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
d3.shape   # formato da array d3

(2, 2, 2)

In [33]:
d3.ndim

3

In [32]:
d3.dtype

dtype('int64')

In [11]:
a = np.array([2,3,4])

b = np.array([2,3,4])

In [12]:
result = np.add(a, b)
print(result)

[4 6 8]


In [9]:
a =  np.array([[2,3,4,5] , [6,7,8,9]])

print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [17]:
# array (linha , coluna)

a[1,2]

np.int64(8)

In [19]:
# buscando a array por linha 0 e 1

a [0, :]

array([2, 3, 4, 5])

In [23]:
# Buscando array pot=r coluna 

a [: , 2]

array([4, 8])